name: quantlite
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - numpy=1.19.5
  - pandas=1.2.4
  - scipy=1.7.0
  - statsmodels=0.13.5
  - scikit-learn=0.24.2
  - numba=0.53.1
  - matplotlib=3.3.4
  - notebook=6.5.2
  - jupyterlab=3.0.14
